services:
  userver-auth:
    container_name: userver-auth
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/code/
    env_file:
      - .env

networks:
  default:
    name: nginx-proxy
    external: true
