services:
  userver-auth:
    container_name: userver-auth
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /code
    command: ["/bin/bash", "./entrypoint.sh"]
    volumes:
      - ./:/code
    env_file:
      - .env
    environment:
      MIGRATE_BIN: ${MIGRATE_BIN:-./out/userver-auth}
      APP_BIN: ${APP_BIN:-./out/userver-auth}

networks:
  default:
    name: nginx-proxy
    external: true
