#!/bin/bash

PGPASSWORD=${POSTGRES_ROOT_PASS} psql -h "${POSTGRES_HOST}" -U "${POSTGRES_ROOT_USER}" -p "${POSTGRES_PORT}" <<EOF
  DROP DATABASE IF EXISTS ${POSTGRES_DB};
  CREATE DATABASE ${POSTGRES_DB};

  DROP DATABASE IF EXISTS ${POSTGRES_DB_TEST};
  CREATE DATABASE ${POSTGRES_DB_TEST};

  DROP OWNED BY ${POSTGRES_USER};
  DROP USER IF EXISTS ${POSTGRES_USER};
  CREATE USER ${POSTGRES_USER} WITH ENCRYPTED PASSWORD '${POSTGRES_PASS}';

  REVOKE ALL PRIVILEGES ON DATABASE postgres FROM ${POSTGRES_USER};
  GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_USER};
  GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB_TEST} TO ${POSTGRES_USER};
\gexec
EOF

rm -rf migrations

python manage.py create_db
python manage.py db init
python manage.py db migrate